export const siteContent = {
  artistName: "KEVIN GEORGE",
  tagline: "Enter the world",
  
  socialLinks: {
    instagram: "https://www.instagram.com/itskevingeorge/",
    twitter: "https://x.com/itskevingeorge",
    tiktok: "https://tiktok.com/kevingeorgeyaps",
    spotify: "https://open.spotify.com/artist/kevingeorge",
    appleMusic: "https://music.apple.com/us/artist/kevin-george/1325859703",
    youtube: "https://youtube.com/@kevingeorge",
  },
  
  featuredRelease: {
    type: "album" as const,
    title: "MY DARLING'S A DEMON",
    subtitle: "The new album out now",
    color: "#1a1a1a",
    link: "/my-darlings-a-demon",
  },
  
  eps: [
    {
      id: "ep-1",
      title: "LOVELAND",
      year: "2018",
      color: "#8B5CF6",
      coverImage: "/images/loveland-ep-cover.png",
      tracklist: [
        "High Like This",
        "My Crew",
        "Drink Or D'usse",
        "Domino Effect",
        "Not Interested",
        "Over",
        "Loving Come Easy"
      ],
      spotifyLink: "https://open.spotify.com/album/0D8VNJjlq0y5NOmFOtdO0f?si=5ssBf8HtSVumgIKYu_tlQw",
      appleMusicLink: "https://music.apple.com/us/album/loveland/1361855858",
    },
    {
      id: "ep-2",
      title: "FORTINA",
      year: "2018",
      color: "#F59E0B",
      coverImage: "/images/fortina-ep-cover.png",
      tracklist: [
        "Lovesick (feat. Billy)",
        "OMG (feat. Billy)",
        "Rolling Stone",
        "Madonna",
        "She Don't Love Me (feat. Gunna)",
        "LA DI DA",
        "MIA"
      ],
      spotifyLink: "https://open.spotify.com/album/2meJNpTO6oKiuLtoFYrqMO?si=i6WhVfn6Rq2DV9Su5e9Ufw",
      appleMusicLink: "https://music.apple.com/us/album/fortina/1410563733",
    },
    {
      id: "ep-3",
      title: "THE HOPELESS ROMANTIC",
      year: "2018",
      color: "#EF4444",
      coverImage: "/images/hopeless-romantic-ep-cover.png",
      tracklist: [
        "Call Me When You're Sober",
        "Need Your Love",
        "You're Just Like Your Mama",
        "Dead Ends (feat. Chandler Elyse)",
        "Everybody Lies",
        "Nobody Knows You Anymore",
        "Perfect Timing"
      ],
      spotifyLink: "https://open.spotify.com/album/0k5V7Haw0fdUqGK8IEoyRo?si=K8EoAdrIQcmJrbIQh1iY8A",
      appleMusicLink: "https://music.apple.com/us/album/hopeless-romantic-ep/1439399188",
    },
    {
      id: "ep-4",
      title: "THREE CAN PLAY, AT LOVE",
      year: "2020",
      color: "#06B6D4",
      coverImage: "/images/three-can-play-cover.png",
      tracklist: [],
      spotifyLink: "https://open.spotify.com/album/7DZsFMZbo535eMeaexDw3p?si=dCktC36aRAaU4mPGZgNVqg",
      appleMusicLink: "https://music.apple.com/us/album/three-can-play-at-love-ep/1503235355",
    },
    {
      id: "ep-5",
      title: "FORTINA II",
      year: "2020",
      color: "#F59E0B",
      coverImage: "/images/fortina-2-ep-cover.jpg",
      tracklist: [],
      spotifyLink: "https://open.spotify.com/album/1r6ijP2axKFch9IG2CALVo?si=bay5orPOQxOCiY6ZMvHz4A",
      appleMusicLink: "https://music.apple.com/us/album/fortina-ii/1525456498",
    },
  ],
  
  singles: [
    // 2025 Singles
    {
      id: "single-half-amazing",
      title: "HALF AMAZING",
      releaseDate: "2025",
      color: "#06B6D4",
      coverImage: "/images/singles/half-amazing.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-all-for-me",
      title: "ALL FOR ME",
      releaseDate: "2025",
      color: "#8B5CF6",
      coverImage: "/images/singles/all-for-me.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-kiss-n-tell",
      title: "KISS N TELL",
      subtitle: "Lost Tapes 2021",
      releaseDate: "2025",
      color: "#E11D48",
      coverImage: "/images/singles/kiss-n-tell.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-sedated",
      title: "SEDATED",
      releaseDate: "2025",
      color: "#7C3AED",
      coverImage: "/images/singles/sedated.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-the-moment",
      title: "THE MOMENT",
      releaseDate: "2025",
      color: "#0891B2",
      coverImage: "/images/singles/the-moment.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-all-my-days",
      title: "ALL MY DAYS",
      subtitle: "Lost Tapes 2020",
      releaseDate: "2025",
      color: "#059669",
      coverImage: "/images/singles/all-my-days.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-save-us",
      title: "SAVE US",
      subtitle: "Lost Tapes 2019",
      releaseDate: "2025",
      color: "#DC2626",
      coverImage: "/images/singles/save-us.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-u-never-needed-me",
      title: "U NEVER NEEDED ME",
      subtitle: "Lost Tapes 2018",
      releaseDate: "2025",
      color: "#CA8A04",
      coverImage: "/images/singles/u-never-needed-me.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-lifes-a-dream",
      title: "LIFE'S A DREAM",
      subtitle: "Lost Tapes 2020",
      releaseDate: "2025",
      color: "#4F46E5",
      coverImage: "/images/singles/lifes-a-dream.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-give-me-a-reason",
      title: "GIVE ME A REASON",
      subtitle: "Lost Tapes 2020",
      releaseDate: "2025",
      color: "#DB2777",
      coverImage: "/images/singles/give-me-a-reason.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-20-feel-like",
      title: "20FEELLIKE",
      subtitle: "Lost Tapes 2018",
      releaseDate: "2025",
      color: "#16A34A",
      coverImage: "/images/singles/20-feel-like.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-by-design",
      title: "BY DESIGN",
      releaseDate: "2025",
      color: "#0E7490",
      coverImage: "/images/singles/by-design.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    // 2024 Singles
    {
      id: "single-new-york",
      title: "NEW YORK",
      releaseDate: "2024",
      color: "#1E293B",
      coverImage: "/images/singles/new-york.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-wished-u-well",
      title: "WISHED U WELL",
      releaseDate: "2024",
      color: "#475569",
      coverImage: "/images/singles/wished-u-well.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-bad-girl",
      title: "BAD GIRL",
      releaseDate: "2024",
      color: "#DC2626",
      coverImage: "/images/singles/bad-girl.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-crazy-bout-u",
      title: "CRAZY BOUT U",
      releaseDate: "2024",
      color: "#A855F7",
      coverImage: "/images/singles/crazy-bout-u.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-floating-away",
      title: "FLOATING AWAY",
      releaseDate: "January 19, 2024",
      color: "#0891B2",
      coverImage: "/images/singles/floating-away.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    // 2023 Singles
    {
      id: "single-left-me",
      title: "LEFT ME",
      releaseDate: "December 15, 2023",
      color: "#0284C7",
      coverImage: "/images/singles/left-me.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com/us/album/left-me-single/1719865501",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-drive-me-to-drink",
      title: "DRIVE ME TO DRINK",
      releaseDate: "August 4, 2023",
      color: "#B45309",
      coverImage: "/images/singles/drive-me-to-drink.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com/us/album/drive-me-to-drink-single/1699835792",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-stay-away",
      title: "STAY AWAY",
      releaseDate: "2023",
      color: "#991B1B",
      coverImage: "/images/singles/stay-away.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-stuntin-on-me",
      title: "STUNTIN' ON ME",
      releaseDate: "2023",
      color: "#7C2D12",
      coverImage: "/images/singles/stuntin-on-me.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    // 2022 Singles
    {
      id: "single-2",
      title: "THE WAVE",
      releaseDate: "March 2, 2022",
      color: "#3B82F6",
      coverImage: "/images/the-wave-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/39bKpYdvmU8Bum1CaBkywD?si=e695d110efd141a4",
      appleMusicLink: "https://music.apple.com/us/album/the-wave-single/1819072158",
      youtubeLink: "https://youtu.be/3k54wHTVkCs?si=RnlFaBG5uMEogtRr",
    },
    {
      id: "single-3",
      title: "THE NUMBER 2",
      releaseDate: "March 17, 2022",
      color: "#8B5CF6",
      coverImage: "/images/the-number-2-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/album/7kBsxDdU4iQebCc53MOXHX?si=Xc85hALDRZCcacAoj7oFjg",
      appleMusicLink: "https://music.apple.com/us/album/the-number-2-single/1819072899",
      youtubeLink: "https://youtu.be/UEnSTqBEmfs?si=flYCd5Xw62ZRxizZ",
    },
    {
      id: "single-4",
      title: "AIN'T BEEN THE SAME",
      releaseDate: "March 31, 2022",
      color: "#EF4444",
      coverImage: "/images/aint-the-same-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/album/6H0b52zQzvtMgFAtMnqh87?si=7pPe5sBITKqfWRrU7-uSOg",
      appleMusicLink: "https://music.apple.com/us/album/aint-been-the-same-single/1818897854",
      youtubeLink: "https://www.youtube.com/watch?v=MM6LUpRRKkQ&list=PLjRJrbFkS4OpNBQQKcDmYRQW79IHqvE2U&index=3",
    },
    {
      id: "single-5",
      title: "WE UP",
      releaseDate: "April 14, 2022",
      color: "#F59E0B",
      coverImage: "/images/we-up-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/4AlO5gehHlO1cbcaLP43kb?si=62811bc950384904",
      appleMusicLink: "https://music.apple.com/us/album/we-up-single/1819072382",
      youtubeLink: "https://www.youtube.com/watch?v=QuCrCer9t4A&list=PLjRJrbFkS4OpNBQQKcDmYRQW79IHqvE2U&index=4",
    },
    {
      id: "single-6",
      title: "WHAT IT TAKES",
      releaseDate: "April 28, 2022",
      color: "#EC4899",
      coverImage: "/images/what-it-takes-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/6M4iuzmsKb0uWVpNWn90JR?si=e4f1dae4ffd046ea",
      appleMusicLink: "https://music.apple.com/us/album/what-it-takes-single/1819072422",
      youtubeLink: "https://youtu.be/DOJcZ_EkAlc?si=Nkl-Q6Jq-W2UrGk-",
    },
    {
      id: "single-7",
      title: "LOST MY MIND",
      releaseDate: "May 12, 2022",
      color: "#6366F1",
      coverImage: "/images/lost-my-mind-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/664G4viX1ROwpRkFvqevIO?si=02f96003067043bd",
      appleMusicLink: "https://music.apple.com/us/album/lost-my-mind-single/1819072330",
      youtubeLink: "https://youtu.be/hUSSb1I7JS4?si=Xax7RmXDS7vMnRvo",
    },
    {
      id: "single-hiccup",
      title: "HICCUP",
      releaseDate: "May 26, 2022",
      color: "#10B981",
      coverImage: "/images/singles/hiccup.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-if-looks-could-kill",
      title: "IF LOOKS COULD KILL",
      releaseDate: "June 9, 2022",
      color: "#DC2626",
      coverImage: "/images/singles/if-looks-could-kill.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-some-nights",
      title: "SOME NIGHTS",
      releaseDate: "June 24, 2022",
      color: "#1F2937",
      coverImage: "/images/singles/some-nights.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-angel-numbers",
      title: "ANGEL NUMBERS",
      releaseDate: "July 7, 2022",
      color: "#7DD3C0",
      coverImage: "/images/singles/angel-numbers.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-cash-in-the-club",
      title: "CASH IN THE CLUB",
      releaseDate: "July 21, 2022",
      color: "#84CC16",
      coverImage: "/images/singles/cash-in-the-club.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-big-man",
      title: "BIG MAN",
      releaseDate: "August 4, 2022",
      color: "#FBBF24",
      coverImage: "/images/singles/big-man.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-super-romantic",
      title: "SUPER ROMANTIC",
      releaseDate: "August 18, 2022",
      color: "#DC2626",
      coverImage: "/images/singles/super-romantic.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-thats-my-woman",
      title: "THAT'S MY WOMAN",
      releaseDate: "September 1, 2022",
      color: "#6366F1",
      coverImage: "/images/singles/thats-my-woman.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-the-way-it-goes",
      title: "THE WAY IT GOES",
      releaseDate: "September 15, 2022",
      color: "#0891B2",
      coverImage: "/images/singles/the-way-it-goes.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-in-with-me",
      title: "IN WITH ME",
      releaseDate: "September 29, 2022",
      color: "#14B8A6",
      coverImage: "/images/singles/in-with-me.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-something-new",
      title: "SOMETHING NEW",
      releaseDate: "2022",
      color: "#065F46",
      coverImage: "/images/singles/something-new.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-lies-to-the-grave",
      title: "LIES TO THE GRAVE",
      releaseDate: "2022",
      color: "#44403C",
      coverImage: "/images/singles/lies-to-the-grave.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-whats-the-problem",
      title: "WHAT'S THE PROBLEM?",
      releaseDate: "2022",
      color: "#713F12",
      coverImage: "/images/singles/whats-the-problem.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    // 2021 Singles
    {
      id: "single-world-on-fire",
      title: "WORLD ON FIRE",
      releaseDate: "2021",
      color: "#EA580C",
      coverImage: "/images/singles/world-on-fire.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-warning-signs",
      title: "WARNING SIGNS",
      subtitle: "feat. Kevin George",
      releaseDate: "2021",
      color: "#F97316",
      coverImage: "/images/singles/warning-signs.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
  ],
  
  products: [
    {
      id: "product-1",
      name: "DEMON TOUR TEE",
      price: "$45",
      color: "#1a1a1a",
      buyLink: "https://shop.kevingeorge.com",
    },
    {
      id: "product-2",
      name: "VINYL - MY DARLING'S A DEMON",
      price: "$35",
      color: "#374151",
      buyLink: "https://shop.kevingeorge.com",
    },
    {
      id: "product-3",
      name: "HOODIE - HEAVEN SENT",
      price: "$75",
      color: "#8B5CF6",
      buyLink: "https://shop.kevingeorge.com",
    },
    {
      id: "product-4",
      name: "POSTER PACK",
      price: "$25",
      color: "#F59E0B",
      buyLink: "https://shop.kevingeorge.com",
    },
  ],
  
  myDarlingsADemon: {
    title: "MY DARLING'S A DEMON",
    subtitle: "The debut album",
    year: "2019",
    description: "A journey through love, loss, and the demons we carry. This album explores the darkness within us all and the light we find in each other.",
    color: "#8B0000",
    tracklist: [
      { number: 1, title: "MDAD" },
      { number: 2, title: "THE WORST" },
      { number: 3, title: "BUSSDOWN" },
      { number: 4, title: "LOVE AT FIRST SIGHT" },
      { number: 5, title: "RED LIPSTICK" },
      { number: 6, title: "BREAK UP SEASON" },
      { number: 7, title: "SORRY" },
      { number: 8, title: "EVERY NIGHT" },
      { number: 9, title: "PLAYING WITH FIRE" },
      { number: 10, title: "REAL LOVE" },
      { number: 11, title: "WANNA BE DOWN" },
      { number: 12, title: "IOU" },
      { number: 13, title: "HIGH NOTE" },
      { number: 14, title: "WHAT'S IT LIKE" },
    ],
    pressQuotes: [
      { quote: "A stunning debut that marks the arrival of a major talent.", source: "Rolling Stone" },
      { quote: "Raw, emotional, and utterly captivating.", source: "Pitchfork" },
      { quote: "Kevin George has created something truly special.", source: "Complex" },
    ],
    spotifyLink: "https://open.spotify.com/album/1Z08UDoHKkFRdbgYV0CLSm?si=S50KA5UqQV69LcJPhuwudw",
    appleMusicLink: "https://music.apple.com",
    youtubeLink: "https://youtube.com",
  },

  everybodysInMyEar: {
    title: "EVERYBODY'S IN MY EAR",
    subtitle: "The second album",
    year: "2021",
    description: "A whimsical journey through the chaos of voices, dreams, and the bittersweet beauty of being heard.",
    coverImage: "/images/everybodys-in-my-ear-cover.png",
    spotifyLink: "https://open.spotify.com/album/6jgwS3qrYF920kSmpuvFck?si=bQCsYSRCRTyuFle3t_XsCw",
    appleMusicLink: "https://music.apple.com/us/album/everybodys-in-my-ear/1819746356",
  },
};

export type EP = typeof siteContent.eps[number];
export type Single = typeof siteContent.singles[number];
export type Product = typeof siteContent.products[number];
