export const siteContent = {
  artistName: "KEVIN GEORGE",
  tagline: "Enter the world",

  socialLinks: {
    instagram: "https://www.instagram.com/itskevingeorge/",
    twitter: "https://x.com/itskevingeorge",
    tiktok: "https://www.tiktok.com/@kevingeorgespam",
    spotify:
      "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI?si=Sc4ymkq7SsamC74NOhPISA",
    appleMusic: "https://music.apple.com/us/artist/kevin-george/1325859703",
    youtube: "https://youtube.com/@kevingeorge",
  },
  
  featuredRelease: {
    type: "album" as const,
    title: "MY DARLING'S A DEMON",
    subtitle: "The new album out now",
    color: "#1a1a1a",
    link: "/my-darlings-a-demon",
  },
  
  eps: [
    {
      id: "ep-1",
      title: "LOVELAND",
      year: "2018",
      color: "#8B5CF6",
      coverImage: "/images/loveland-ep-cover.png",
      tracklist: [
        "High Like This",
        "My Crew",
        "Drink Or D'usse",
        "Domino Effect",
        "Not Interested",
        "Over",
        "Loving Come Easy"
      ],
      spotifyLink: "https://open.spotify.com/album/0D8VNJjlq0y5NOmFOtdO0f?si=5ssBf8HtSVumgIKYu_tlQw",
      appleMusicLink: "https://music.apple.com/us/album/loveland/1361855858",
    },
    {
      id: "ep-2",
      title: "FORTINA",
      year: "2018",
      color: "#F59E0B",
      coverImage: "/images/fortina-ep-cover.png",
      tracklist: [
        "Lovesick (feat. Billy)",
        "OMG (feat. Billy)",
        "Rolling Stone",
        "Madonna",
        "She Don't Love Me (feat. Gunna)",
        "LA DI DA",
        "MIA"
      ],
      spotifyLink: "https://open.spotify.com/album/2meJNpTO6oKiuLtoFYrqMO?si=i6WhVfn6Rq2DV9Su5e9Ufw",
      appleMusicLink: "https://music.apple.com/us/album/fortina/1410563733",
    },
    {
      id: "ep-3",
      title: "THE HOPELESS ROMANTIC",
      year: "2018",
      color: "#EF4444",
      coverImage: "/images/hopeless-romantic-ep-cover.png",
      tracklist: [
        "Call Me When You're Sober",
        "Need Your Love",
        "You're Just Like Your Mama",
        "Dead Ends (feat. Chandler Elyse)",
        "Everybody Lies",
        "Nobody Knows You Anymore",
        "Perfect Timing"
      ],
      spotifyLink: "https://open.spotify.com/album/0k5V7Haw0fdUqGK8IEoyRo?si=K8EoAdrIQcmJrbIQh1iY8A",
      appleMusicLink: "https://music.apple.com/us/album/hopeless-romantic-ep/1439399188",
    },
    {
      id: "album-my-darlings-a-demon",
      title: "MY DARLING'S A DEMON",
      year: "2019",
      color: "#8B0000",
      coverImage: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02834c801d5016927635ac80b1",
      tracklist: [
        "Wait",
        "All of Me",
        "Wish You Were Here",
        "I Better Find Your Love",
        "Don't Sleep Without Me",
        "Lay It On Me",
        "Switch Up",
        "Sweet Darling",
        "Off the Wall",
        "Reeses",
        "Why Would I Love Again",
        "Last Night I Lost Reason",
        "You Won't Get Me Back",
        "I'm Not The Best For You",
      ],
      spotifyLink: "https://open.spotify.com/album/1Z08UDoHKkFRdbgYV0CLSm?si=S50KA5UqQV69LcJPhuwudw",
      appleMusicLink: "https://music.apple.com/us/artist/kevin-george/1325859703",
    },
    {
      id: "ep-4",
      title: "THREE CAN PLAY, AT LOVE",
      year: "2020",
      color: "#06B6D4",
      coverImage: "/images/three-can-play-cover.png",
      tracklist: [],
      spotifyLink: "https://open.spotify.com/album/7DZsFMZbo535eMeaexDw3p?si=dCktC36aRAaU4mPGZgNVqg",
      appleMusicLink: "https://music.apple.com/us/album/three-can-play-at-love-ep/1503235355",
    },
    {
      id: "ep-5",
      title: "FORTINA II",
      year: "2020",
      color: "#F59E0B",
      coverImage: "/images/fortina-2-ep-cover.jpg",
      tracklist: [],
      spotifyLink: "https://open.spotify.com/album/1r6ijP2axKFch9IG2CALVo?si=bay5orPOQxOCiY6ZMvHz4A",
      appleMusicLink: "https://music.apple.com/us/album/fortina-ii/1525456498",
    },
    {
      id: "ep-everybodys-in-my-ear",
      title: "EVERYBODY'S IN MY EAR",
      year: "2021",
      color: "#111111",
      coverImage: "/images/everybodys-in-my-ear-cover.png",
      tracklist: [
        "INTRO",
        "EVERYBODY'S IN MY EAR",
        "ALL IN MY HEAD",
        "OUTSIDE",
        "SUPER SWEET",
        "CONFUSED",
        "DREAMSTATE",
      ],
      spotifyLink: "https://open.spotify.com/album/6jgwS3qrYF920kSmpuvFck?si=bQCsYSRCRTyuFle3t_XsCw",
      appleMusicLink: "https://music.apple.com/us/album/everybodys-in-my-ear/1819746356",
    },
    {
      id: "ep-stay-away",
      title: "STAY AWAY",
      year: "2023",
      color: "#111111",
      coverImage: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02b3c42aba6403fc5a7225d140",
      tracklist: [
        "STAY AWAY",
        "JOHN DOE",
        "Fly Low",
        "Baby Wouldn't Have Me Waiting",
        "OFF THE SHROOMS",
      ],
      spotifyLink: "https://open.spotify.com/album/30yggwAnGnsArpQh19bI1Z?si=F8kMbYrmRCikd1neF2AVnQ",
      appleMusicLink: "https://music.apple.com/us/album/stay-away-ep/1716361550",
    },
  ],

  singles: [
    // 2025 Singles
    {
      id: "single-kiss-n-tell-2025",
      title: "KISS N TELL",
      subtitle: "Lost Tapes 2021",
      releaseDate: "December 12, 2025",
      color: "#E11D48",
      coverImage: "/images/singles/kiss-n-tell.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-sedated-2025",
      title: "SEDATED",
      releaseDate: "December 5, 2025",
      color: "#7C3AED",
      coverImage: "/images/singles/sedated.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-all-my-days-2025",
      title: "ALL MY DAYS",
      subtitle: "Lost Tapes 2020",
      releaseDate: "September 19, 2025",
      color: "#059669",
      coverImage: "/images/singles/all-my-days.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-save-us-2025",
      title: "SAVE US",
      subtitle: "Lost Tapes 2019",
      releaseDate: "September 5, 2025",
      color: "#DC2626",
      coverImage: "/images/singles/save-us.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-u-never-needed-me-2025",
      title: "U NEVER NEEDED ME",
      subtitle: "Lost Tapes 2018",
      releaseDate: "August 29, 2025",
      color: "#CA8A04",
      coverImage: "/images/singles/u-never-needed-me.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-lifes-a-dream-2025",
      title: "LIFE'S A DREAM",
      subtitle: "Lost Tapes 2020",
      releaseDate: "August 22, 2025",
      color: "#4F46E5",
      coverImage: "/images/singles/lifes-a-dream.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-give-me-a-reason-2025",
      title: "GIVE ME A REASON",
      subtitle: "Lost Tapes 2020",
      releaseDate: "August 15, 2025",
      color: "#DB2777",
      coverImage: "/images/singles/give-me-a-reason.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-ghosttown-2025",
      title: "GHOSTTOWN",
      subtitle: "Lost Tapes 2020",
      releaseDate: "August 8, 2025",
      color: "#475569",
      coverImage: "/images/singles/ghosttown.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-anything-goes-2025",
      title: "ANYTHING GOES",
      subtitle: "Lost Tapes 2018",
      releaseDate: "August 1, 2025",
      color: "#14B8A6",
      coverImage: "/images/singles/anything-goes.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-20-feel-like-2025",
      title: "20FEELLIKE",
      subtitle: "Lost Tapes 2018",
      releaseDate: "July 25, 2025",
      color: "#16A34A",
      coverImage: "/images/singles/20-feel-like.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-by-design-2025",
      title: "BY DESIGN",
      releaseDate: "May 23, 2025",
      color: "#0E7490",
      coverImage: "/images/singles/by-design.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-all-for-me-2025",
      title: "ALL FOR ME",
      releaseDate: "May 9, 2025",
      color: "#8B5CF6",
      coverImage: "/images/singles/all-for-me.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-half-amazing",
      title: "HALF AMAZING",
      releaseDate: "April 25, 2025",
      color: "#06B6D4",
      coverImage: "/images/singles/half-amazing.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    // 2024 Singles
    {
      id: "single-new-york",
      title: "NEW YORK",
      releaseDate: "August 30, 2024",
      color: "#1E293B",
      coverImage: "/images/singles/new-york.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-wished-u-well",
      title: "WISHED U WELL",
      releaseDate: "August 16, 2024",
      color: "#475569",
      coverImage: "/images/singles/wished-u-well.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-bad-girl",
      title: "BAD GIRL",
      releaseDate: "August 9, 2024",
      color: "#DC2626",
      coverImage: "/images/singles/bad-girl.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-crazy-bout-u",
      title: "CRAZY BOUT U",
      releaseDate: "August 2, 2024",
      color: "#A855F7",
      coverImage: "/images/singles/crazy-bout-u.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-rock-n-roll",
      title: "ROCK N ROLL",
      releaseDate: "July 26, 2024",
      color: "#8B5CF6",
      coverImage: "/images/singles/rock-n-roll.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-ghost",
      title: "GHOST",
      releaseDate: "July 12, 2024",
      color: "#64748B",
      coverImage: "/images/singles/ghost.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-watch-me-bleed",
      title: "WATCH ME BLEED",
      releaseDate: "February 9, 2024",
      color: "#B91C1C",
      coverImage: "/images/singles/watch-me-bleed.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-floating-away",
      title: "FLOATING AWAY",
      releaseDate: "January 19, 2024",
      color: "#0891B2",
      coverImage: "/images/singles/floating-away.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    // 2023 Singles
    {
      id: "single-its-colder-now",
      title: "IT'S COLDER NOW, BUT IT IS WHAT IT IS",
      releaseDate: "December 25, 2023",
      color: "#60A5FA",
      coverImage: "/images/singles/its-colder-now.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-left-me",
      title: "LEFT ME",
      releaseDate: "December 15, 2023",
      color: "#0284C7",
      coverImage: "/images/singles/left-me.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com/us/album/left-me-single/1719865501",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-fly-low",
      title: "FLY LOW",
      releaseDate: "September 29, 2023",
      color: "#6366F1",
      coverImage: "/images/singles/fly-low.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-swamp",
      title: "SWAMP",
      releaseDate: "September 15, 2023",
      color: "#059669",
      coverImage: "/images/singles/swamp.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-go-ahead",
      title: "GO AHEAD",
      subtitle: "ft Daniel Allan & Bkaye",
      releaseDate: "September 8, 2023",
      color: "#8B5CF6",
      coverImage: "/images/singles/go-ahead.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-am-i-to-blame",
      title: "AM I TO BLAME",
      releaseDate: "September 1, 2023",
      color: "#DC2626",
      coverImage: "/images/singles/am-i-to-blame.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-breaking-the-bank",
      title: "BREAKING THE BANK",
      releaseDate: "August 18, 2023",
      color: "#16A34A",
      coverImage: "/images/singles/breaking-the-bank.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-drive-me-to-drink",
      title: "DRIVE ME TO DRINK",
      releaseDate: "August 4, 2023",
      color: "#B45309",
      coverImage: "/images/singles/drive-me-to-drink.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com/us/album/drive-me-to-drink-single/1699835792",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-youre-in-my-head-again",
      title: "YOU'RE IN MY HEAD AGAIN",
      releaseDate: "June 26, 2023",
      color: "#7C3AED",
      coverImage: "/images/singles/youre-in-my-head-again.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-baby-wouldnt-have-me-waiting",
      title: "BABY WOULDN'T HAVE ME WAITING",
      releaseDate: "June 16, 2023",
      color: "#DB2777",
      coverImage: "/images/singles/baby-wouldnt-have-me-waiting.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-way-back",
      title: "WAY BACK",
      releaseDate: "June 9, 2023",
      color: "#F59E0B",
      coverImage: "/images/singles/way-back.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-secrets-safe",
      title: "SECRETS SAFE",
      releaseDate: "June 1, 2023",
      color: "#0891B2",
      coverImage: "/images/singles/secrets-safe.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-slow-your-roll",
      title: "SLOW YOUR ROLL",
      releaseDate: "May 25, 2023",
      color: "#EF4444",
      coverImage: "/images/singles/slow-your-roll.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-john-doe",
      title: "JOHN DOE",
      releaseDate: "May 18, 2023",
      color: "#475569",
      coverImage: "/images/singles/john-doe.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-off-the-shrooms",
      title: "OFF THE SHROOMS",
      releaseDate: "May 4, 2023",
      color: "#84CC16",
      coverImage: "/images/singles/off-the-shrooms.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-what-u-like",
      title: "WHAT U LIKE",
      releaseDate: "February 10, 2023",
      color: "#EC4899",
      coverImage: "/images/singles/what-u-like.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-ball",
      title: "BALL!",
      subtitle: "Ft Daniel Allan",
      releaseDate: "January 27, 2023",
      color: "#F97316",
      coverImage: "/images/singles/ball.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-so-long",
      title: "SO LONG",
      releaseDate: "January 19, 2023",
      color: "#0EA5E9",
      coverImage: "/images/singles/so-long.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-holy-matrimony",
      title: "HOLY MATRIMONY",
      releaseDate: "January 5, 2023",
      color: "#A855F7",
      coverImage: "/images/singles/holy-matrimony.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-stay-away",
      title: "STAY AWAY",
      releaseDate: "2023",
      color: "#991B1B",
      coverImage: "/images/singles/stay-away.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    // 2022 Singles
    {
      id: "single-2",
      title: "THE WAVE",
      releaseDate: "March 2, 2022",
      color: "#3B82F6",
      coverImage: "/images/the-wave-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/39bKpYdvmU8Bum1CaBkywD?si=e695d110efd141a4",
      appleMusicLink: "https://music.apple.com/us/album/the-wave-single/1819072158",
      youtubeLink: "https://youtu.be/3k54wHTVkCs?si=RnlFaBG5uMEogtRr",
    },
    {
      id: "single-3",
      title: "THE NUMBER 2",
      releaseDate: "March 17, 2022",
      color: "#8B5CF6",
      coverImage: "/images/the-number-2-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/album/7kBsxDdU4iQebCc53MOXHX?si=Xc85hALDRZCcacAoj7oFjg",
      appleMusicLink: "https://music.apple.com/us/album/the-number-2-single/1819072899",
      youtubeLink: "https://youtu.be/UEnSTqBEmfs?si=flYCd5Xw62ZRxizZ",
    },
    {
      id: "single-4",
      title: "AIN'T BEEN THE SAME",
      releaseDate: "March 31, 2022",
      color: "#EF4444",
      coverImage: "/images/aint-the-same-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/album/6H0b52zQzvtMgFAtMnqh87?si=7pPe5sBITKqfWRrU7-uSOg",
      appleMusicLink: "https://music.apple.com/us/album/aint-been-the-same-single/1818897854",
      youtubeLink: "https://www.youtube.com/watch?v=MM6LUpRRKkQ&list=PLjRJrbFkS4OpNBQQKcDmYRQW79IHqvE2U&index=3",
    },
    {
      id: "single-5",
      title: "WE UP",
      releaseDate: "April 14, 2022",
      color: "#F59E0B",
      coverImage: "/images/we-up-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/4AlO5gehHlO1cbcaLP43kb?si=62811bc950384904",
      appleMusicLink: "https://music.apple.com/us/album/we-up-single/1819072382",
      youtubeLink: "https://www.youtube.com/watch?v=QuCrCer9t4A&list=PLjRJrbFkS4OpNBQQKcDmYRQW79IHqvE2U&index=4",
    },
    {
      id: "single-6",
      title: "WHAT IT TAKES",
      releaseDate: "April 28, 2022",
      color: "#EC4899",
      coverImage: "/images/what-it-takes-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/6M4iuzmsKb0uWVpNWn90JR?si=e4f1dae4ffd046ea",
      appleMusicLink: "https://music.apple.com/us/album/what-it-takes-single/1819072422",
      youtubeLink: "https://youtu.be/DOJcZ_EkAlc?si=Nkl-Q6Jq-W2UrGk-",
    },
    {
      id: "single-7",
      title: "LOST MY MIND",
      releaseDate: "May 12, 2022",
      color: "#6366F1",
      coverImage: "/images/lost-my-mind-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/664G4viX1ROwpRkFvqevIO?si=02f96003067043bd",
      appleMusicLink: "https://music.apple.com/us/album/lost-my-mind-single/1819072330",
      youtubeLink: "https://youtu.be/hUSSb1I7JS4?si=Xax7RmXDS7vMnRvo",
    },
    {
      id: "single-hiccup",
      title: "HICCUP",
      releaseDate: "May 26, 2022",
      color: "#10B981",
      coverImage: "/images/singles/hiccup.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-if-looks-could-kill",
      title: "IF LOOKS COULD KILL",
      releaseDate: "June 9, 2022",
      color: "#DC2626",
      coverImage: "/images/singles/if-looks-could-kill.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-some-nights",
      title: "SOME NIGHTS",
      releaseDate: "June 24, 2022",
      color: "#1F2937",
      coverImage: "/images/singles/some-nights.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-angel-numbers",
      title: "ANGEL NUMBERS",
      releaseDate: "July 7, 2022",
      color: "#7DD3C0",
      coverImage: "/images/singles/angel-numbers.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-cash-in-the-club",
      title: "CASH IN THE CLUB",
      releaseDate: "July 21, 2022",
      color: "#84CC16",
      coverImage: "/images/singles/cash-in-the-club.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-big-man",
      title: "BIG MAN",
      releaseDate: "August 4, 2022",
      color: "#FBBF24",
      coverImage: "/images/singles/big-man.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-super-romantic",
      title: "SUPER ROMANTIC",
      releaseDate: "August 18, 2022",
      color: "#DC2626",
      coverImage: "/images/singles/super-romantic.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-thats-my-woman",
      title: "THAT'S MY WOMAN",
      releaseDate: "September 1, 2022",
      color: "#FB923C",
      coverImage: "/images/singles/thats-my-woman.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-the-way-it-goes",
      title: "THE WAY IT GOES",
      releaseDate: "September 15, 2022",
      color: "#B45309",
      coverImage: "/images/singles/the-way-it-goes.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-in-with-me",
      title: "IN WITH ME",
      releaseDate: "September 29, 2022",
      color: "#818CF8",
      coverImage: "/images/singles/in-with-me.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-i-like-that",
      title: "I LIKE THAT",
      releaseDate: "December 22, 2022",
      color: "#10B981",
      coverImage: "/images/singles/i-like-that.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-something-new",
      title: "SOMETHING NEW",
      releaseDate: "2022",
      color: "#065F46",
      coverImage: "/images/singles/something-new.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    // 2021 Singles
    {
      id: "single-world-on-fire",
      title: "WORLD ON FIRE",
      subtitle: "feat. Johan Lenox",
      releaseDate: "2021",
      color: "#EA580C",
      coverImage: "/images/singles/world-on-fire.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-warning-signs",
      title: "WARNING SIGNS",
      subtitle: "feat. Whetan",
      releaseDate: "2021",
      color: "#F97316",
      coverImage: "/images/singles/warning-signs.jpg",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/artist/0UFKnbRkop5zKvIHhbnMCI",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
  ],
  
  products: [
    {
      id: "product-1",
      name: "DEMON TOUR TEE",
      price: "$45",
      color: "#1a1a1a",
      buyLink: "https://shop.kevingeorge.com",
    },
    {
      id: "product-2",
      name: "VINYL - MY DARLING'S A DEMON",
      price: "$35",
      color: "#374151",
      buyLink: "https://shop.kevingeorge.com",
    },
    {
      id: "product-3",
      name: "HOODIE - HEAVEN SENT",
      price: "$75",
      color: "#8B5CF6",
      buyLink: "https://shop.kevingeorge.com",
    },
    {
      id: "product-4",
      name: "POSTER PACK",
      price: "$25",
      color: "#F59E0B",
      buyLink: "https://shop.kevingeorge.com",
    },
  ],
  
  myDarlingsADemon: {
    title: "MY DARLING'S A DEMON",
    subtitle: "The debut album",
    year: "2019",
    description: "A journey through love, loss, and the demons we carry. This album explores the darkness within us all and the light we find in each other.",
    color: "#8B0000",
    tracklist: [
      { number: 1, title: "Wait" },
      { number: 2, title: "All of Me" },
      { number: 3, title: "Wish You Were Here" },
      { number: 4, title: "I Better Find Your Love" },
      { number: 5, title: "Don't Sleep Without Me" },
      { number: 6, title: "Lay It On Me" },
      { number: 7, title: "Switch Up" },
      { number: 8, title: "Sweet Darling" },
      { number: 9, title: "Off the Wall" },
      { number: 10, title: "Reeses" },
      { number: 11, title: "Why Would I Love Again" },
      { number: 12, title: "Last Night I Lost Reason" },
      { number: 13, title: "You Won't Get Me Back" },
      { number: 14, title: "I'm Not The Best For You" },
    ],
    pressQuotes: [
      { quote: "A stunning debut that marks the arrival of a major talent.", source: "Rolling Stone" },
      { quote: "Raw, emotional, and utterly captivating.", source: "Pitchfork" },
      { quote: "Kevin George has created something truly special.", source: "Complex" },
    ],
    spotifyLink: "https://open.spotify.com/album/1Z08UDoHKkFRdbgYV0CLSm?si=S50KA5UqQV69LcJPhuwudw",
    appleMusicLink: "https://music.apple.com",
    youtubeLink: "https://youtube.com",
  },

  everybodysInMyEar: {
    title: "EVERYBODY'S IN MY EAR",
    subtitle: "The second album",
    year: "2021",
    description: "A whimsical journey through the chaos of voices, dreams, and the bittersweet beauty of being heard.",
    coverImage: "/images/everybodys-in-my-ear-cover.png",
    spotifyLink: "https://open.spotify.com/album/6jgwS3qrYF920kSmpuvFck?si=bQCsYSRCRTyuFle3t_XsCw",
    appleMusicLink: "https://music.apple.com/us/album/everybodys-in-my-ear/1819746356",
  },
};

export type EP = typeof siteContent.eps[number];
export type Single = typeof siteContent.singles[number];
export type Product = typeof siteContent.products[number];
