export const siteContent = {
  artistName: "KEVIN GEORGE",
  tagline: "Enter the world",
  
  socialLinks: {
    instagram: "https://instagram.com/kevingeorge",
    twitter: "https://twitter.com/kevingeorge",
    tiktok: "https://tiktok.com/@kevingeorge",
    spotify: "https://open.spotify.com/artist/kevingeorge",
    appleMusic: "https://music.apple.com/artist/kevingeorge",
    youtube: "https://youtube.com/@kevingeorge",
  },
  
  featuredRelease: {
    type: "album" as const,
    title: "MY DARLING'S A DEMON",
    subtitle: "The new album out now",
    color: "#1a1a1a",
    link: "/my-darlings-a-demon",
  },
  
  eps: [
    {
      id: "ep-1",
      title: "LOVELAND",
      year: "2018",
      color: "#8B5CF6",
      coverImage: "/images/loveland-ep-cover.png",
      tracklist: [
        "High Like This",
        "My Crew",
        "Drink Or D'usse",
        "Domino Effect",
        "Not Interested",
        "Over",
        "Loving Come Easy"
      ],
      spotifyLink: "https://open.spotify.com/album/0D8VNJjlq0y5NOmFOtdO0f?si=5ssBf8HtSVumgIKYu_tlQw",
      appleMusicLink: "https://music.apple.com/us/album/loveland/1361855858",
    },
    {
      id: "ep-2",
      title: "FORTINA",
      year: "2018",
      color: "#F59E0B",
      coverImage: "/images/fortina-ep-cover.png",
      tracklist: [
        "Lovesick (feat. Billy)",
        "OMG (feat. Billy)",
        "Rolling Stone",
        "Madonna",
        "She Don't Love Me (feat. Gunna)",
        "LA DI DA",
        "MIA"
      ],
      spotifyLink: "https://open.spotify.com/album/2meJNpTO6oKiuLtoFYrqMO?si=i6WhVfn6Rq2DV9Su5e9Ufw",
      appleMusicLink: "https://music.apple.com/us/album/fortina/1410563733",
    },
    {
      id: "ep-3",
      title: "THE HOPELESS ROMANTIC",
      year: "2018",
      color: "#EF4444",
      coverImage: "/images/hopeless-romantic-ep-cover.png",
      tracklist: [
        "Call Me When You're Sober",
        "Need Your Love",
        "You're Just Like Your Mama",
        "Dead Ends (feat. Chandler Elyse)",
        "Everybody Lies",
        "Nobody Knows You Anymore",
        "Perfect Timing"
      ],
      spotifyLink: "https://open.spotify.com/album/0k5V7Haw0fdUqGK8IEoyRo?si=K8EoAdrIQcmJrbIQh1iY8A",
      appleMusicLink: "https://music.apple.com/us/album/hopeless-romantic-ep/1439399188",
    },
    {
      id: "ep-4",
      title: "THREE CAN PLAY, AT LOVE",
      year: "2020",
      color: "#06B6D4",
      coverImage: "/images/three-can-play-cover.png",
      tracklist: [],
      spotifyLink: "https://open.spotify.com/album/7DZsFMZbo535eMeaexDw3p?si=dCktC36aRAaU4mPGZgNVqg",
      appleMusicLink: "https://music.apple.com/us/album/three-can-play-at-love-ep/1503235355",
    },
    {
      id: "ep-5",
      title: "FORTINA II",
      year: "2020",
      color: "#F59E0B",
      coverImage: "/images/fortina-2-ep-cover.jpg",
      tracklist: [],
      spotifyLink: "https://open.spotify.com/album/1r6ijP2axKFch9IG2CALVo?si=bay5orPOQxOCiY6ZMvHz4A",
      appleMusicLink: "https://music.apple.com/us/album/fortina-ii/1525456498",
    },
  ],
  
  singles: [
    {
      id: "single-1",
      title: "She Don't Love Me",
      subtitle: "ft. Gunna",
      releaseDate: "June 22, 2018",
      color: "#10B981",
      coverImage: "/images/she-dont-love-me-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com",
      appleMusicLink: "https://music.apple.com",
      youtubeLink: "https://youtube.com",
    },
    {
      id: "single-2",
      title: "THE WAVE",
      releaseDate: "March 2, 2022",
      color: "#3B82F6",
      coverImage: "/images/the-wave-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/39bKpYdvmU8Bum1CaBkywD?si=e695d110efd141a4",
      appleMusicLink: "https://music.apple.com/us/album/the-wave-single/1819072158",
      youtubeLink: "https://youtu.be/3k54wHTVkCs?si=RnlFaBG5uMEogtRr",
    },
    {
      id: "single-3",
      title: "THE NUMBER 2",
      releaseDate: "March 17, 2022",
      color: "#8B5CF6",
      coverImage: "/images/the-number-2-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/album/7kBsxDdU4iQebCc53MOXHX?si=Xc85hALDRZCcacAoj7oFjg",
      appleMusicLink: "https://music.apple.com/us/album/the-number-2-single/1819072899",
      youtubeLink: "https://youtu.be/UEnSTqBEmfs?si=flYCd5Xw62ZRxizZ",
    },
    {
      id: "single-4",
      title: "AIN'T BEEN THE SAME",
      releaseDate: "March 31, 2022",
      color: "#EF4444",
      coverImage: "/images/aint-the-same-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/album/6H0b52zQzvtMgFAtMnqh87?si=7pPe5sBITKqfWRrU7-uSOg",
      appleMusicLink: "https://music.apple.com/us/album/aint-been-the-same-single/1818897854",
      youtubeLink: "https://www.youtube.com/watch?v=MM6LUpRRKkQ&list=PLjRJrbFkS4OpNBQQKcDmYRQW79IHqvE2U&index=3",
    },
    {
      id: "single-5",
      title: "WE UP",
      releaseDate: "April 14, 2022",
      color: "#F59E0B",
      coverImage: "/images/we-up-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/4AlO5gehHlO1cbcaLP43kb?si=62811bc950384904",
      appleMusicLink: "https://music.apple.com/us/album/we-up-single/1819072382",
      youtubeLink: "https://www.youtube.com/watch?v=QuCrCer9t4A&list=PLjRJrbFkS4OpNBQQKcDmYRQW79IHqvE2U&index=4",
    },
    {
      id: "single-6",
      title: "What It Takes",
      releaseDate: "April 28, 2022",
      color: "#EC4899",
      coverImage: "/images/what-it-takes-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/6M4iuzmsKb0uWVpNWn90JR?si=e4f1dae4ffd046ea",
      appleMusicLink: "https://music.apple.com/us/album/what-it-takes-single/1819072422",
      youtubeLink: "https://youtu.be/DOJcZ_EkAlc?si=Nkl-Q6Jq-W2UrGk-",
    },
    {
      id: "single-7",
      title: "Lost My Mind",
      releaseDate: "May 12, 2022",
      color: "#6366F1",
      coverImage: "/images/lost-my-mind-cover.png",
      isPinned: false,
      spotifyLink: "https://open.spotify.com/track/664G4viX1ROwpRkFvqevIO?si=02f96003067043bd",
      appleMusicLink: "https://music.apple.com/us/album/lost-my-mind-single/1819072330",
      youtubeLink: "https://youtu.be/hUSSb1I7JS4?si=Xax7RmXDS7vMnRvo",
    },
  ],
  
  products: [
    {
      id: "product-1",
      name: "DEMON TOUR TEE",
      price: "$45",
      color: "#1a1a1a",
      buyLink: "https://shop.kevingeorge.com",
    },
    {
      id: "product-2",
      name: "VINYL - MY DARLING'S A DEMON",
      price: "$35",
      color: "#374151",
      buyLink: "https://shop.kevingeorge.com",
    },
    {
      id: "product-3",
      name: "HOODIE - HEAVEN SENT",
      price: "$75",
      color: "#8B5CF6",
      buyLink: "https://shop.kevingeorge.com",
    },
    {
      id: "product-4",
      name: "POSTER PACK",
      price: "$25",
      color: "#F59E0B",
      buyLink: "https://shop.kevingeorge.com",
    },
  ],
  
  myDarlingsADemon: {
    title: "MY DARLING'S A DEMON",
    subtitle: "The debut album",
    year: "2019",
    description: "A journey through love, loss, and the demons we carry. This album explores the darkness within us all and the light we find in each other.",
    color: "#8B0000",
    tracklist: [
      { number: 1, title: "MDAD" },
      { number: 2, title: "THE WORST" },
      { number: 3, title: "BUSSDOWN" },
      { number: 4, title: "LOVE AT FIRST SIGHT" },
      { number: 5, title: "RED LIPSTICK" },
      { number: 6, title: "BREAK UP SEASON" },
      { number: 7, title: "SORRY" },
      { number: 8, title: "EVERY NIGHT" },
      { number: 9, title: "PLAYING WITH FIRE" },
      { number: 10, title: "REAL LOVE" },
      { number: 11, title: "WANNA BE DOWN" },
      { number: 12, title: "IOU" },
      { number: 13, title: "HIGH NOTE" },
      { number: 14, title: "WHAT'S IT LIKE" },
    ],
    pressQuotes: [
      { quote: "A stunning debut that marks the arrival of a major talent.", source: "Rolling Stone" },
      { quote: "Raw, emotional, and utterly captivating.", source: "Pitchfork" },
      { quote: "Kevin George has created something truly special.", source: "Complex" },
    ],
    spotifyLink: "https://open.spotify.com/album/1Z08UDoHKkFRdbgYV0CLSm?si=S50KA5UqQV69LcJPhuwudw",
    appleMusicLink: "https://music.apple.com",
    youtubeLink: "https://youtube.com",
  },

  everybodysInMyEar: {
    title: "EVERYBODY'S IN MY EAR",
    subtitle: "The second album",
    year: "2021",
    description: "A whimsical journey through the chaos of voices, dreams, and the bittersweet beauty of being heard.",
    coverImage: "/images/everybodys-in-my-ear-cover.png",
    spotifyLink: "https://open.spotify.com/album/6jgwS3qrYF920kSmpuvFck?si=bQCsYSRCRTyuFle3t_XsCw",
    appleMusicLink: "https://music.apple.com/us/album/everybodys-in-my-ear/1819746356",
  },
};

export type EP = typeof siteContent.eps[number];
export type Single = typeof siteContent.singles[number];
export type Product = typeof siteContent.products[number];
